// Each entry: category + Italian + English. Same index in both languages,
// so switching language keeps the measured outcome.
window.PHRASES = [
  // ---------- Vita / Life ----------
  { c: "life", it: "Il tuo futuro è in sovrapposizione: smetti di fissarlo e inizia a viverlo.", en: "Your future is in superposition: stop staring at it and start living it." },
  { c: "life", it: "Finché non apri il frigo, la cena è sia pronta che non pronta.", en: "Until you open the fridge, dinner is both ready and not ready." },
  { c: "life", it: "Oggi la probabilità di un bel momento è alta. Non sprecare la misura.", en: "Today the probability of a good moment is high. Don't waste the measurement." },
  { c: "life", it: "Le persone giuste si riconoscono: con loro anche il rumore sembra musica.", en: "You'll know the right people: with them, even noise sounds like music." },
  { c: "life", it: "Il caffè non risolve i problemi, ma li rende osservabili.", en: "Coffee doesn't solve problems, but it makes them observable." },
  { c: "life", it: "Non serve un computer quantistico per capire che ti meriti una vacanza.", en: "You don't need a quantum computer to know you deserve a vacation." },
  { c: "life", it: "Ogni tanto spegni il telefono. Anche i qubit hanno bisogno di isolamento.", en: "Turn off your phone sometimes. Even qubits need isolation." },
  { c: "life", it: "Una porta chiusa è solo un'altra base di misura.", en: "A closed door is just another measurement basis." },
  { c: "life", it: "Chi divide la pizza con te alle due di notte è entangled con te per sempre.", en: "Whoever shares pizza with you at 2 a.m. is entangled with you forever." },
  { c: "life", it: "Rimandare è sovrapposizione. Farlo oggi è collasso. Scegli il collasso.", en: "Putting it off is superposition. Doing it today is collapse. Choose collapse." },
  { c: "life", it: "I piani cambiano. Anche gli elettroni cambiano orbitale, e nessuno si lamenta.", en: "Plans change. Electrons change orbitals too, and nobody complains." },
  { c: "life", it: "Un sorriso ha fedeltà del 100%: nessun errore da correggere.", en: "A smile has 100% fidelity: no errors to correct." },
  { c: "life", it: "La felicità non si può clonare, ma si può teletrasportare a chi ti sta accanto.", en: "Happiness can't be cloned, but it can be teleported to the people next to you." },
  { c: "life", it: "Domani sarà una bella giornata. Con probabilità 0,87.", en: "Tomorrow will be a great day. With probability 0.87." },
  { c: "life", it: "Lascia andare ciò che non puoi osservare.", en: "Let go of what you cannot observe." },
  { c: "life", it: "Il segreto dell'equilibrio: un po' di stabilità, un po' di caos e tanto buon cibo.", en: "The secret of balance: some stability, some chaos and lots of good food." },
  { c: "life", it: "Dormire otto ore è il miglior algoritmo di error correction.", en: "Eight hours of sleep is the best error-correction algorithm." },
  { c: "life", it: "Gli amici veri sono come i qubit ben calibrati: rari e preziosi.", en: "True friends are like well-calibrated qubits: rare and precious." },
  { c: "life", it: "Quella cosa che temi ha una probabilità più bassa di quanto pensi.", en: "The thing you fear has a lower probability than you think." },
  { c: "life", it: "Non confrontare la tua vita con quella degli altri: siete misurati in basi diverse.", en: "Don't compare your life to others': you're measured in different bases." },
  { c: "life", it: "Oggi qualcuno penserà a te. È entanglement, non telepatia.", en: "Someone will think of you today. It's entanglement, not telepathy." },
  { c: "life", it: "Viaggia appena puoi: anche la funzione d'onda ama espandersi.", en: "Travel whenever you can: wave functions love to spread out too." },
  { c: "life", it: "Il momento perfetto non esiste. Esiste il momento misurato.", en: "There is no perfect moment. There is only the measured one." },
  { c: "life", it: "Brinda più spesso: ogni brindisi è un piccolo esperimento di interferenza costruttiva.", en: "Toast more often: every toast is a small experiment in constructive interference." },

  // ---------- Università / University ----------
  { c: "uni", it: "Il tuo relatore è in sovrapposizione tra «ottimo lavoro» e «rivediamo il capitolo 3».", en: "Your advisor is in a superposition of “great work” and “let's revisit chapter 3”." },
  { c: "uni", it: "La sessione d'esami passa. I meme sulla sessione d'esami restano.", en: "Exam season ends. Exam-season memes are forever." },
  { c: "uni", it: "Il 18 e il 30 e lode coesistono finché non viene pubblicato il voto.", en: "A pass and an A+ coexist until the grade is published." },
  { c: "uni", it: "Il vero esame è arrivare puntuali alla lezione delle 8:30.", en: "The real exam is making it on time to the 8:30 a.m. lecture." },
  { c: "uni", it: "La biblioteca ha un campo gravitazionale: entri per un'ora, esci all'orario di chiusura.", en: "The library has its own gravity: you go in for an hour, you leave at closing time." },
  { c: "uni", it: "Hai già fatto la cosa più difficile: iniziare. Ora tocca alla seconda: finire.", en: "You already did the hardest part: starting. Now the second hardest: finishing." },
  { c: "uni", it: "Le slide del prof sono un sistema chiuso: nessuna informazione ne esce.", en: "The professor's slides are a closed system: no information escapes." },
  { c: "uni", it: "Ricevimento studenti: l'unico posto dove il tempo si dilata davvero.", en: "Office hours: the only place where time truly dilates." },
  { c: "uni", it: "Il codice che funziona al primo tentativo esiste solo in teoria.", en: "Code that works on the first try exists only in theory." },
  { c: "uni", it: "«Tanto lo studio tutto il giorno prima»: ultime parole famose in ogni universo parallelo.", en: "“I'll study it all the day before”: famous last words in every parallel universe." },
  { c: "uni", it: "La laurea è un traguardo e, allo stesso tempo, una nuova condizione iniziale.", en: "Graduation is a finish line and, at the same time, a brand-new initial condition." },
  { c: "uni", it: "Dottore oggi, debugger per sempre.", en: "Graduate today, debugger forever." },
  { c: "uni", it: "Il gruppo di studio è entanglement puro: se uno non ha capito, non ha capito nessuno.", en: "A study group is pure entanglement: if one person didn't get it, nobody did." },
  { c: "uni", it: "La bibliografia è infinita. La scadenza no.", en: "The bibliography is infinite. The deadline isn't." },
  { c: "uni", it: "Prima o poi capirai l'esercizio 4. Probabilmente sotto la doccia.", en: "You'll understand exercise 4 eventually. Probably in the shower." },
  { c: "uni", it: "Le macchinette dell'università sono il vero motore della ricerca.", en: "The university vending machines are the true engine of research." },
  { c: "uni", it: "Ogni CFU è un quanto di fatica.", en: "Every credit is a quantum of effort." },
  { c: "uni", it: "La tesi più bella è quella consegnata.", en: "The best thesis is a submitted thesis." },
  { c: "uni", it: "Hai superato Analisi 1: ora puoi superare qualsiasi cosa.", en: "You survived Calculus 1: now you can survive anything." },
  { c: "uni", it: "Il tuo futuro collega sta ancora cercando di installare LaTeX.", en: "Your future coworker is still trying to install LaTeX." },
  { c: "uni", it: "Le notti in bianco prima dell'esame non sono quantistiche: si sentono eccome.", en: "All-nighters before an exam aren't quantum: you definitely feel them." },
  { c: "uni", it: "Il curriculum è pronto quando smetti di aggiornarlo. Cioè mai.", en: "Your CV is ready when you stop updating it. So, never." },
  { c: "uni", it: "Fai rete: anche i qubit, da soli, non combinano molto.", en: "Network: even qubits don't do much on their own." },
  { c: "uni", it: "L'esame orale è il più antico esperimento di misura distruttiva.", en: "The oral exam is the oldest destructive-measurement experiment." },

  // ---------- AI ----------
  { c: "ai", it: "Anche l'AI ha le allucinazioni. Tu almeno hai una laurea.", en: "Even AI hallucinates. At least you have a degree." },
  { c: "ai", it: "Chiedi all'AI di scrivere il tuo futuro. Poi riscrivilo meglio tu.", en: "Ask an AI to write your future. Then rewrite it better yourself." },
  { c: "ai", it: "Il prompt perfetto non esiste. Esiste quello abbastanza buono e un altro caffè.", en: "There's no perfect prompt. Just a good-enough one and another coffee." },
  { c: "ai", it: "Un giorno le macchine penseranno. Speriamo non come noi il lunedì mattina.", en: "One day machines will think. Hopefully not like we do on Monday mornings." },
  { c: "ai", it: "L'AI impara dai dati. Tu impara dagli errori: costano meno di una GPU.", en: "AI learns from data. You learn from mistakes: they cost less than a GPU." },
  { c: "ai", it: "Nessun modello linguistico può prevedere la tua prossima mossa. Questo oracolo sì. Forse.", en: "No language model can predict your next move. This oracle can. Maybe." },
  { c: "ai", it: "Se l'AI ti ruberà il lavoro, assicurati di essere tu ad addestrarla.", en: "If AI is going to take your job, make sure you're the one training it." },
  { c: "ai", it: "Il tuo intuito ha più parametri di qualsiasi rete neurale.", en: "Your intuition has more parameters than any neural network." },
  { c: "ai", it: "Overfitting: quando studi solo gli esami degli anni passati.", en: "Overfitting: when you only study past exams." },
  { c: "ai", it: "Non farti trattare come un token: tu sei l'intero contesto.", en: "Don't let anyone treat you like a token: you're the whole context." },
  { c: "ai", it: "La discesa del gradiente insegna: un piccolo passo alla volta, nella direzione giusta.", en: "Gradient descent teaches us: one small step at a time, in the right direction." },
  { c: "ai", it: "Anche le reti neurali hanno bisogno di una pausa. Si chiama dropout.", en: "Even neural networks need a break. It's called dropout." },
  { c: "ai", it: "Il tuo learning rate è perfetto: né troppo veloce, né troppo lento.", en: "Your learning rate is just right: not too fast, not too slow." },
  { c: "ai", it: "Ricordati di chiamare casa. Nessuna AI può farlo al posto tuo.", en: "Remember to call home. No AI can do that for you." },
  { c: "ai", it: "Un'AI quantistica risponderebbe a questa domanda in tutti i modi possibili contemporaneamente.", en: "A quantum AI would answer this question in every possible way at once." },
  { c: "ai", it: "La vera intelligenza è sapere quando chiudere il portatile.", en: "True intelligence is knowing when to close the laptop." },
  { c: "ai", it: "Il tuo dataset di esperienze è unico. Nessun modello può replicarlo.", en: "Your dataset of experiences is unique. No model can replicate it." },
  { c: "ai", it: "Se una macchina supera il test di Turing, offrile un caffè: se lo è meritato.", en: "If a machine passes the Turing test, buy it a coffee: it earned it." },
  { c: "ai", it: "Attention is all you need. Anche nella vita.", en: "Attention is all you need. In life, too." },
  { c: "ai", it: "Le macchine hanno la potenza di calcolo, tu hai l'ironia. Vinci tu.", en: "Machines have computing power, you have irony. You win." },
  { c: "ai", it: "Il bias più pericoloso è credere di non averne.", en: "The most dangerous bias is believing you don't have one." },
  { c: "ai", it: "Nemmeno il chatbot più avanzato sa ordinare la pizza come piace a te.", en: "Not even the most advanced chatbot can order pizza the way you like it." },

  // ---------- Quantum ----------
  { c: "quantum", it: "Non esiste fallimento, solo decoerenza. Riprova.", en: "There's no failure, only decoherence. Try again." },
  { c: "quantum", it: "Il gatto di Schrödinger sta bene. Probabilmente.", en: "Schrödinger's cat is fine. Probably." },
  { c: "quantum", it: "Sei in sovrapposizione di tutte le persone che potresti diventare.", en: "You're in a superposition of everyone you could become." },
  { c: "quantum", it: "Un qubit non sceglie: aspetta il momento giusto per essere misurato.", en: "A qubit doesn't choose: it waits for the right moment to be measured." },
  { c: "quantum", it: "Heisenberg direbbe: puoi sapere dove sei o dove stai andando. Non entrambe le cose.", en: "Heisenberg would say: you can know where you are or where you're going. Not both." },
  { c: "quantum", it: "L'effetto tunnel esiste: anche le barriere più alte si possono attraversare.", en: "Quantum tunneling is real: even the highest barriers can be crossed." },
  { c: "quantum", it: "La tua energia oggi è allo stato fondamentale. Serve un fotone di caffè.", en: "Your energy today is in the ground state. You need a photon of coffee." },
  { c: "quantum", it: "Gli opposti si attraggono, ma le particelle entangled si capiscono al volo.", en: "Opposites attract, but entangled particles understand each other instantly." },
  { c: "quantum", it: "Un gate di Hadamard al giorno toglie la noia di torno.", en: "A Hadamard gate a day keeps boredom away." },
  { c: "quantum", it: "Il futuro non è scritto: è una funzione d'onda.", en: "The future isn't written: it's a wave function." },
  { c: "quantum", it: "La misura cambia il sistema. Anche il tuo sguardo cambia le persone.", en: "Measurement changes the system. Your gaze changes people too." },
  { c: "quantum", it: "Il teorema di no-cloning lo conferma: sei unico.", en: "The no-cloning theorem confirms it: you're one of a kind." },
  { c: "quantum", it: "Anche Feynman diceva che nessuno capisce la meccanica quantistica. Sei in ottima compagnia.", en: "Even Feynman said nobody understands quantum mechanics. You're in great company." },
  { c: "quantum", it: "Quando tutto sembra bloccato, prova a cambiare base.", en: "When everything seems stuck, try changing basis." },
  { c: "quantum", it: "Il vuoto quantistico non è mai vuoto. Nemmeno le tue giornate più tranquille.", en: "The quantum vacuum is never empty. Neither are your quietest days." },
  { c: "quantum", it: "Una sovrapposizione dura poco: goditela finché puoi.", en: "Superposition doesn't last long: enjoy it while you can." },
  { c: "quantum", it: "Spin up! Oggi si sale.", en: "Spin up! Today we rise." },
  { c: "quantum", it: "Il principio di indeterminazione vale anche per i weekend: più li pianifichi, meno li vivi.", en: "The uncertainty principle applies to weekends too: the more you plan them, the less you live them." },
  { c: "quantum", it: "Collassa con stile.", en: "Collapse in style." },
  { c: "quantum", it: "Tra 0 e 1 ci sono infiniti stati. Non accontentarti del binario.", en: "There are infinite states between 0 and 1. Don't settle for binary." },
  { c: "quantum", it: "I computer quantistici risolveranno problemi impossibili. I tuoi, invece, li risolvi già da solo.", en: "Quantum computers will solve impossible problems. Yours, you already solve on your own." },
  { c: "quantum", it: "Lo stato fondamentale è sopravvalutato: eccitati un po'.", en: "The ground state is overrated: get a little excited." },
  { c: "quantum", it: "Non ti serve un'interpretazione a molti mondi: questo è già quello giusto.", en: "You don't need the many-worlds interpretation: this one is already the right one." },

  // ---------- Tesi / Thesis ----------
  { c: "thesis", it: "Il rumore racconta segreti a chi sa ascoltarlo.", en: "Noise tells secrets to those who know how to listen." },
  { c: "thesis", it: "Il rumore non è sempre un problema. A volte è informazione.", en: "Noise isn't always a problem. Sometimes it's information." },
  { c: "thesis", it: "Ogni sistema ha un side-channel. Anche il cuore.", en: "Every system has a side channel. Even the heart." },
  { c: "thesis", it: "La coupling map della tua vita si scopre un collegamento alla volta.", en: "The coupling map of your life is revealed one connection at a time." },
  { c: "thesis", it: "Non tutti i qubit sono connessi, ma quelli giusti sì.", en: "Not every qubit is connected, but the right ones are." },
  { c: "thesis", it: "Crosstalk rilevato: qualcuno sta parlando bene di te.", en: "Crosstalk detected: someone's saying nice things about you." },
  { c: "thesis", it: "Siamo nell'era NISQ: rumorosa, imperfetta e piena di possibilità. Proprio come la vita.", en: "We live in the NISQ era: noisy, imperfect and full of potential. Just like life." },
  { c: "thesis", it: "Anche il computer più potente ha un rumore di fondo. Accetta il tuo.", en: "Even the most powerful computer has background noise. Embrace yours." },
  { c: "thesis", it: "Un buon attaccante osserva. Un ottimo ingegnere ha osservato prima di lui.", en: "A good attacker observes. A great engineer has already observed." },
  { c: "thesis", it: "Chi studia il rumore impara a sentire il silenzio.", en: "Those who study noise learn to hear silence." },
  { c: "thesis", it: "Le connessioni nascoste sono spesso le più forti.", en: "Hidden connections are often the strongest." },
  { c: "thesis", it: "Calibrazione completata: sei pronto per il mondo.", en: "Calibration complete: you're ready for the world." },
  { c: "thesis", it: "Error rate basso, ambizioni alte.", en: "Low error rate, high ambitions." },
  { c: "thesis", it: "Nessuna coupling map è perfetta: si lavora con i collegamenti che si hanno.", en: "No coupling map is perfect: you work with the links you have." },
  { c: "thesis", it: "Il tuo segnale è più forte del rumore.", en: "Your signal is stronger than the noise." },
  { c: "thesis", it: "Inferenza riuscita: il tuo futuro ha una topologia molto interessante.", en: "Inference successful: your future has a very interesting topology." },
  { c: "thesis", it: "Il rumore attorno a te non definisce il tuo stato.", en: "The noise around you doesn't define your state." },
  { c: "thesis", it: "Gate a due qubit: le cose migliori si fanno in coppia.", en: "Two-qubit gates: the best things are done in pairs." },
  { c: "thesis", it: "La sicurezza perfetta non esiste, ma l'amicizia vera ci va molto vicino.", en: "Perfect security doesn't exist, but true friendship comes very close." },
  { c: "thesis", it: "Il Dott. Casaburi approva questa misura.", en: "Dr. Casaburi approves this measurement." },
  { c: "thesis", it: "Questo oracolo è stato calibrato da un ingegnere informatico. Fidati.", en: "This oracle was calibrated by a computer engineer. Trust it." },
  { c: "thesis", it: "Non serve un attacco side-channel per capire che oggi sei di buon umore.", en: "You don't need a side-channel attack to tell you're in a good mood today." },
  { c: "thesis", it: "Ogni rumore ha la sua firma. Lascia anche tu la tua.", en: "Every noise has a signature. Leave yours too." }
];
