// Predictions. `id` is stable and can be targeted by the URL bias (see README),
// `c` is the category. Add new entries at the end of their category with a new id.
window.PHRASES = [
  // ---------- Amore / Love ----------
  { id: "love-01", c: "love", it: "Presto qualcuno ti farà battere il cuore più veloce di un qubit sotto un gate di Hadamard.", en: "Soon someone will make your heart race faster than a qubit under a Hadamard gate." },
  { id: "love-02", c: "love", it: "Nei prossimi mesi troverai una persona con cui sarai entangled: quello che senti tu, lo sentirà anche lei.", en: "In the coming months you'll find someone you're entangled with: whatever you feel, they'll feel too." },
  { id: "love-03", c: "love", it: "Un messaggio che aspetti da tempo arriverà proprio quando smetterai di controllare il telefono.", en: "A message you've been waiting for will arrive the moment you stop checking your phone." },
  { id: "love-04", c: "love", it: "Il tuo prossimo appuntamento collasserà nello stato migliore possibile.", en: "Your next date will collapse into the best possible state." },
  { id: "love-05", c: "love", it: "Qualcuno sta pensando a te in questo preciso momento. Una misura lo confermerà presto.", en: "Someone is thinking about you right now. A measurement will confirm it soon." },
  { id: "love-06", c: "love", it: "Una vecchia fiamma tornerà a farsi viva, ma il tuo stato sarà già cambiato.", en: "An old flame will reappear, but your state will already have changed." },
  { id: "love-07", c: "love", it: "Entro la fine dell'anno qualcuno ti farà una dichiarazione inaspettata.", en: "Before the year is out, someone will surprise you with a confession." },
  { id: "love-08", c: "love", it: "La tua storia d'amore avrà più colpi di scena di un esperimento della doppia fenditura.", en: "Your love story will have more plot twists than a double-slit experiment." },
  { id: "love-09", c: "love", it: "Un incontro casuale a una festa si rivelerà tutt'altro che casuale.", en: "A random encounter at a party will turn out to be anything but random." },
  { id: "love-10", c: "love", it: "Riceverai un complimento sincero dalla persona da cui meno te lo aspetti.", en: "You'll get a sincere compliment from the person you least expect." },
  { id: "love-11", c: "love", it: "Il prossimo anno festeggerai un anniversario che oggi nemmeno immagini.", en: "Next year you'll celebrate an anniversary you can't even imagine today." },
  { id: "love-12", c: "love", it: "Due stati che sembrano incompatibili troveranno un equilibrio: in amore, il compromesso ti porterà lontano.", en: "Two states that seem incompatible will find a balance: in love, compromise will take you far." },

  // ---------- Lavoro / Work ----------
  { id: "work-01", c: "work", it: "Entro un anno riceverai una proposta di lavoro che cambierà la tua traiettoria.", en: "Within a year you'll get a job offer that changes your trajectory." },
  { id: "work-02", c: "work", it: "Il tuo prossimo colloquio andrà meglio di quanto prevedano tutte le simulazioni.", en: "Your next interview will go better than any simulation predicts." },
  { id: "work-03", c: "work", it: "Presto qualcuno ti affiderà un progetto importante. E dirai di sì.", en: "Soon someone will trust you with an important project. And you'll say yes." },
  { id: "work-04", c: "work", it: "Una tua idea, oggi ancora in sovrapposizione, diventerà realtà nei prossimi mesi.", en: "An idea of yours, still in superposition today, will become real in the coming months." },
  { id: "work-05", c: "work", it: "Arriverà un aumento. La probabilità sale ogni volta che lo chiedi.", en: "A raise is coming. The probability goes up every time you ask." },
  { id: "work-06", c: "work", it: "Un giorno lavorerai da un posto con vista sul mare.", en: "One day you'll work from a place with a sea view." },
  { id: "work-07", c: "work", it: "Il lunedì smetterà di farti paura: troverai un lavoro che ti piace davvero.", en: "Mondays will stop scaring you: you'll find a job you truly love." },
  { id: "work-08", c: "work", it: "Un collega diventerà un amico per la vita.", en: "A coworker will become a lifelong friend." },
  { id: "work-09", c: "work", it: "La tua prossima riunione sarà breve. È la predizione meno probabile, ma non impossibile.", en: "Your next meeting will be short. It's the least likely prediction, but not impossible." },
  { id: "work-10", c: "work", it: "Presto qualcuno ti chiederà un consiglio professionale: sarà l'inizio di qualcosa di grande.", en: "Soon someone will ask for your professional advice: it'll be the start of something big." },
  { id: "work-11", c: "work", it: "Avvierai un progetto tutto tuo, e il rumore iniziale si trasformerà in segnale.", en: "You'll start a project of your own, and the initial noise will turn into signal." },
  { id: "work-12", c: "work", it: "Il tuo nome comparirà in un posto dove non ti aspetteresti mai di vederlo.", en: "Your name will appear somewhere you'd never expect to see it." },

  // ---------- Studio / Study ----------
  { id: "study-01", c: "study", it: "Il prossimo esame che affronterai collasserà su un voto più alto del previsto.", en: "The next exam you take will collapse onto a higher grade than expected." },
  { id: "study-02", c: "study", it: "Un giorno sarai tu a festeggiare una laurea, con una bomboniera tutta tua.", en: "One day you'll be the one celebrating a graduation, with a party favor all your own." },
  { id: "study-03", c: "study", it: "Imparerai una nuova lingua prima di quanto pensi.", en: "You'll learn a new language sooner than you think." },
  { id: "study-04", c: "study", it: "Presto capirai finalmente una cosa che ti sembrava impossibile.", en: "Soon you'll finally understand something that seemed impossible." },
  { id: "study-05", c: "study", it: "Un corso che inizierai per curiosità cambierà la tua carriera.", en: "A course you start out of curiosity will change your career." },
  { id: "study-06", c: "study", it: "Il tuo relatore, presente o futuro, ti risponderà entro 24 ore. Miracoli quantistici.", en: "Your advisor, current or future, will reply within 24 hours. Quantum miracles." },
  { id: "study-07", c: "study", it: "Insegnerai qualcosa a qualcuno e scoprirai di saperla meglio di quanto credevi.", en: "You'll teach something to someone and discover you know it better than you thought." },
  { id: "study-08", c: "study", it: "Un libro che leggerai quest'anno ti resterà dentro per sempre.", en: "A book you'll read this year will stay with you forever." },
  { id: "study-09", c: "study", it: "Supererai l'esame, o la sfida, che rimandi da troppo tempo.", en: "You'll pass the exam, or the challenge, you've been putting off for too long." },
  { id: "study-10", c: "study", it: "Presto ti iscriverai a qualcosa di nuovo: un corso, un master, una scuola di ballo. Darai la colpa a questo oracolo.", en: "Soon you'll sign up for something new: a course, a master's, dance classes. You'll blame this oracle." },
  { id: "study-11", c: "study", it: "Nei prossimi giorni avrai un'intuizione geniale. Probabilmente sotto la doccia.", en: "In the next few days you'll have a brilliant insight. Probably in the shower." },
  { id: "study-12", c: "study", it: "Un giorno qualcuno citerà un tuo lavoro.", en: "One day someone will cite your work." },

  // ---------- Viaggi / Travel ----------
  { id: "travel-01", c: "travel", it: "Entro il prossimo anno farai il viaggio che rimandi da troppo tempo.", en: "By next year you'll take the trip you've been postponing for too long." },
  { id: "travel-02", c: "travel", it: "Presto ti ritroverai dall'altra parte del mondo, come per effetto tunnel.", en: "Soon you'll find yourself on the other side of the world, as if by quantum tunneling." },
  { id: "travel-03", c: "travel", it: "Un volo in ritardo ti farà incontrare una persona importante.", en: "A delayed flight will make you meet someone important." },
  { id: "travel-04", c: "travel", it: "Il tuo prossimo viaggio sarà improvvisato, e sarà il migliore di sempre.", en: "Your next trip will be improvised, and it'll be the best ever." },
  { id: "travel-05", c: "travel", it: "Vedrai l'aurora boreale. L'esito è certo, la data no.", en: "You'll see the northern lights. The outcome is certain, the date isn't." },
  { id: "travel-06", c: "travel", it: "Un weekend fuori porta si trasformerà in un ricordo indimenticabile.", en: "A weekend getaway will turn into an unforgettable memory." },
  { id: "travel-07", c: "travel", it: "Vivrai per un periodo in un'altra città, e ti piacerà più del previsto.", en: "You'll live in another city for a while, and you'll like it more than expected." },
  { id: "travel-08", c: "travel", it: "Perderai una coincidenza, ma troverai una strada migliore.", en: "You'll miss a connection, but you'll find a better path." },
  { id: "travel-09", c: "travel", it: "Assaggerai un piatto in un paese lontano e ne parlerai per anni.", en: "You'll taste a dish in a faraway country and talk about it for years." },
  { id: "travel-10", c: "travel", it: "La tua valigia arriverà a destinazione. Insieme a te. Stavolta.", en: "Your suitcase will reach your destination. Together with you. This time." },
  { id: "travel-11", c: "travel", it: "Un viaggio con gli amici diventerà una leggenda da raccontare per anni.", en: "A trip with friends will become a legend you'll retell for years." },
  { id: "travel-12", c: "travel", it: "Presto riceverai l'invito a un matrimonio in un posto bellissimo.", en: "Soon you'll be invited to a wedding in a beautiful place." },

  // ---------- Fortuna / Luck ----------
  { id: "luck-01", c: "luck", it: "Nei prossimi giorni troverai dei soldi in una tasca che non controllavi da mesi.", en: "In the next few days you'll find money in a pocket you haven't checked in months." },
  { id: "luck-02", c: "luck", it: "La fortuna è in sovrapposizione sopra di te: domani collasserà dalla tua parte.", en: "Luck is in superposition above you: tomorrow it'll collapse in your favor." },
  { id: "luck-03", c: "luck", it: "Vincerai qualcosa. Forse non la lotteria, ma qualcosa sì.", en: "You'll win something. Maybe not the lottery, but something." },
  { id: "luck-04", c: "luck", it: "Il prossimo semaforo sarà verde. E anche quello dopo.", en: "The next traffic light will be green. And the one after that." },
  { id: "luck-05", c: "luck", it: "Una porta che sembrava chiusa si aprirà all'improvviso.", en: "A door that seemed closed will suddenly open." },
  { id: "luck-06", c: "luck", it: "Questa settimana tutto andrà come previsto. Per una volta.", en: "This week everything will go according to plan. For once." },
  { id: "luck-07", c: "luck", it: "Troverai parcheggio al primo colpo proprio quando ne avrai più bisogno.", en: "You'll find a parking spot on the first try exactly when you need it most." },
  { id: "luck-08", c: "luck", it: "Una piccola coincidenza ti porterà una grande occasione.", en: "A small coincidence will bring you a big opportunity." },
  { id: "luck-09", c: "luck", it: "Il prossimo anno sarà il tuo anno: le probabilità sono tutte dalla tua parte.", en: "Next year will be your year: the odds are all on your side." },
  { id: "luck-10", c: "luck", it: "Riceverai una buona notizia prima della fine del mese.", en: "You'll get good news before the end of the month." },
  { id: "luck-11", c: "luck", it: "Qualcosa che hai perso tornerà da te.", en: "Something you lost will come back to you." },
  { id: "luck-12", c: "luck", it: "Presto sarai nel posto giusto al momento giusto. Heisenberg permettendo.", en: "Soon you'll be in the right place at the right time. Heisenberg permitting." },

  // ---------- Amicizia / Friends ----------
  { id: "friends-01", c: "friends", it: "Ritroverai un'amicizia che credevi persa.", en: "You'll reconnect with a friendship you thought was lost." },
  { id: "friends-02", c: "friends", it: "Entro cinque minuti brinderai alla salute del Dott. Casaburi.", en: "Within five minutes you'll raise a glass to Dr. Casaburi." },
  { id: "friends-03", c: "friends", it: "Presto organizzerai una cena che finirà molto più tardi del previsto.", en: "Soon you'll host a dinner that ends much later than planned." },
  { id: "friends-04", c: "friends", it: "Una persona che hai appena conosciuto diventerà importante nella tua vita.", en: "Someone you've just met will become important in your life." },
  { id: "friends-05", c: "friends", it: "Un vecchio amico ti chiamerà proprio quando ne avrai bisogno.", en: "An old friend will call you right when you need it." },
  { id: "friends-06", c: "friends", it: "Qualcuno ti chiederà di fare da testimone al suo matrimonio.", en: "Someone will ask you to stand by their side at their wedding." },
  { id: "friends-07", c: "friends", it: "Il tuo gruppo di amici resterà entangled anche a migliaia di chilometri di distanza.", en: "Your group of friends will stay entangled even thousands of kilometers apart." },
  { id: "friends-08", c: "friends", it: "Presto riderai così tanto da non riuscire a respirare.", en: "Soon you'll laugh so hard you can't breathe." },
  { id: "friends-09", c: "friends", it: "Qualcuno ti ringrazierà per un favore che hai già dimenticato.", en: "Someone will thank you for a favor you've already forgotten." },
  { id: "friends-10", c: "friends", it: "Questa festa sarà l'inizio di una nuova amicizia.", en: "This party will be the start of a new friendship." },
  { id: "friends-11", c: "friends", it: "Un gruppo WhatsApp nato stasera durerà più di molte relazioni.", en: "A group chat born tonight will outlast many relationships." },
  { id: "friends-12", c: "friends", it: "Tra dieci anni ricorderai questa giornata con le stesse persone che hai accanto adesso.", en: "Ten years from now you'll remember this day with the same people who are next to you now." },

  // ---------- Tecnologia / Tech ----------
  { id: "tech-01", c: "tech", it: "Presto un'AI risolverà un tuo problema in cinque secondi. Il sesto lo passerai a chiederti come facevi prima.", en: "Soon an AI will solve one of your problems in five seconds. You'll spend the sixth wondering how you managed before." },
  { id: "tech-02", c: "tech", it: "Il tuo prossimo codice funzionerà al primo tentativo. Goditi il momento: è raro.", en: "Your next piece of code will work on the first try. Enjoy the moment: it's rare." },
  { id: "tech-03", c: "tech", it: "Entro dieci anni userai un computer quantistico senza nemmeno accorgertene.", en: "Within ten years you'll use a quantum computer without even noticing." },
  { id: "tech-04", c: "tech", it: "Oggi la batteria del telefono durerà fino a sera. È dalla tua parte.", en: "Today your phone battery will last until evening. It's on your side." },
  { id: "tech-05", c: "tech", it: "Un'AI ti suggerirà qualcosa di perfetto, ma l'idea migliore resterà la tua.", en: "An AI will suggest something perfect, but the best idea will still be yours." },
  { id: "tech-06", c: "tech", it: "Presto risolverai un bug che ti tormenta da giorni. Era un punto e virgola.", en: "Soon you'll fix a bug that's been haunting you for days. It was a semicolon." },
  { id: "tech-07", c: "tech", it: "Il Wi-Fi funzionerà alla perfezione proprio quando ne avrai più bisogno.", en: "The Wi-Fi will work perfectly exactly when you need it most." },
  { id: "tech-08", c: "tech", it: "Un giorno racconterai ai tuoi nipoti che i computer, una volta, conoscevano solo 0 e 1.", en: "One day you'll tell your grandkids that computers once knew only 0s and 1s." },
  { id: "tech-09", c: "tech", it: "Farai il backup di qualcosa di importante. Un attimo prima che serva.", en: "You'll back up something important. Just before you need it." },
  { id: "tech-10", c: "tech", it: "Un tuo post diventerà virale. Non sarà quello che ti aspetti.", en: "One of your posts will go viral. It won't be the one you expect." },
  { id: "tech-11", c: "tech", it: "La prossima password che inventerai sarà impossibile da indovinare. Anche per te.", en: "The next password you create will be impossible to guess. Even for you." },
  { id: "tech-12", c: "tech", it: "Nei prossimi anni la tecnologia ti aprirà una strada che oggi non esiste ancora.", en: "In the coming years technology will open a path for you that doesn't exist yet." },

  // ---------- Vita / Life ----------
  { id: "life-01", c: "life", it: "Domani ti sveglierai con più energia del solito.", en: "Tomorrow you'll wake up with more energy than usual." },
  { id: "life-02", c: "life", it: "Presto prenderai una decisione importante, e sarà quella giusta.", en: "Soon you'll make an important decision, and it'll be the right one." },
  { id: "life-03", c: "life", it: "Questo weekend ti concederai la pausa che meriti da tempo.", en: "This weekend you'll give yourself the break you've long deserved." },
  { id: "life-04", c: "life", it: "Nei prossimi mesi inizierai un'abitudine che ti cambierà in meglio.", en: "In the coming months you'll start a habit that changes you for the better." },
  { id: "life-05", c: "life", it: "La settimana prossima dirai di sì a qualcosa di nuovo, e non te ne pentirai.", en: "Next week you'll say yes to something new, and you won't regret it." },
  { id: "life-06", c: "life", it: "Presto avrai una casa che sentirai davvero tua.", en: "Soon you'll have a home that truly feels like yours." },
  { id: "life-07", c: "life", it: "Un sogno che avevi messo da parte tornerà in sovrapposizione. Stavolta collasserà nello stato giusto.", en: "A dream you set aside will come back into superposition. This time it'll collapse the right way." },
  { id: "life-08", c: "life", it: "Il tuo futuro ha un'ampiezza di probabilità altissima di essere felice.", en: "Your future has a very high probability amplitude of being happy." },
  { id: "life-09", c: "life", it: "Entro un anno guarderai indietro e sorriderai per quanta strada hai fatto.", en: "Within a year you'll look back and smile at how far you've come." },
  { id: "life-10", c: "life", it: "Presto qualcuno cucinerà per te il tuo piatto preferito.", en: "Soon someone will cook your favorite dish for you." },
  { id: "life-11", c: "life", it: "Troverai il coraggio di fare quella cosa che rimandi da troppo tempo.", en: "You'll find the courage to do that thing you've been putting off for too long." },
  { id: "life-12", c: "life", it: "Stanotte dormirai benissimo. Lo dice la meccanica quantistica, più o meno.", en: "Tonight you'll sleep wonderfully. Quantum mechanics says so, more or less." }
];
